# Generated by Django 5.0.4 on 2024-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
