# Generated by Django 5.0.4 on 2024-06-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comments_last_update_review_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
