# Generated by Django 5.0.4 on 2024-06-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_review_first_published_alter_review_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='first_published',
            field=models.DateTimeField(null=True),
        ),
    ]
